# Generated by Django 4.0.4 on 2022-06-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
